# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kaye <kaye@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/16 19:09:32 by kaye              #+#    #+#              #
#    Updated: 2021/05/12 19:15:33 by kaye             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:latest

COPY . /APP
WORKDIR /APP

RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf \
	&& apk update \
	&& apk add --no-cache openrc telegraf \
	&& apk add --no-cache mariadb mariadb-common mariadb-client

# telegraf config
RUN mkdir /etc/telegraf/
COPY ./srcs/telegraf.conf /etc/telegraf.conf

EXPOSE 3306

CMD ["/bin/sh", "./srcs/init.sh"]