apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql-http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: svc_mysql
        imagePullPolicy: Never
        env:
        - name: WP_PASS
          valueFrom:
            secretKeyRef:
              name: password
              key: wppass
        - name: ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: password
              key: adminpass
        ports:
        - containerPort: 3306
          name: mysql-http
        livenessProbe:
          exec:
            command:
              - sh
              - /APP/srcs/livenessprobe.sh
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: pvc-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi