version: "3.8"

services:
  # back
  back-end:
    build:
      dockerfile: Dockerfile
      context: ./back-end
      target: development
    restart: always
    volumes:
      - ./back-end:/camagru/back-end/
      - back-end-node-modules:/camagru/back-end/node_modules/
      - back-end-upload:/camagru/back-end/upload
    command: npm run serve
    environment:
      DB_CONN: ${DB_CONN}
      DB_NAME: ${DB_NAME}
      DB_USER_COLL_NAME: ${DB_USER_COLL_NAME}
      DB_FILE_COLL_NAME: ${DB_FILE_COLL_NAME}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      FRONT_URL: ${FRONT_URL}
      API_URL: ${API_URL}
    ports:
      - "3000:3000"
    networks:
      - camagru_net

  # front
  front-end:
    build:
      dockerfile: Dockerfile
      context: ./front-end
      target: development
    restart: always
    volumes:
      - ./front-end:/camagru/front-end/
      - front-end-node-modules:/camagru/front-end/node_modules/
    command: node front.server.js
    depends_on:
      - back_end
    ports:
      - "5050:5050"
    networks:
      - camagru_net

volumes:
  back-end-node-modules:
  back-end-upload:
  front-end-node-modules:

networks:
  camagru_net:
     driver: bridge

