FROM python:3.11-slim

RUN apt-get update && apt-get install -y build-essential postgresql postgresql-client

WORKDIR /app

ENV PYTHONPATH /app
ENV PYTHONUNBUFFERED 1

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY src .

