apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: svc_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 20000
        - containerPort: 20001
        - containerPort: 20002
        - containerPort: 20003
        - containerPort: 20004
        - containerPort: 20005
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    # metallb.universe.tf/allow-shared-ip: <key> : use the same IP address for each service with the same key
    metallb.universe.tf/allow-shared-ip: universal-ip
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - port: 20
    targetPort: 20
    nodePort: 20
    name: ftps-port-20
  - port: 21
    targetPort: 21
    nodePort: 21
    name: ftps-port-21
  - port: 20000
    targetPort: 20000
    nodePort: 20000
    name: ftps-pasif-port-20000
  - port: 20001
    targetPort: 20001
    nodePort: 20001
    name: ftps-pasif-port-20001
  - port: 20002
    targetPort: 20002
    nodePort: 20002
    name: ftps-pasif-port-20002
  - port: 20003
    targetPort: 20003
    nodePort: 20003
    name: ftps-pasif-port-20003
  - port: 20004
    targetPort: 20004
    nodePort: 20004
    name: ftps-pasif-port-20004
  - port: 20005
    targetPort: 20005
    nodePort: 20005
    name: ftps-pasif-port--20005