# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kaye <kaye@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/16 19:08:46 by kaye              #+#    #+#              #
#    Updated: 2021/05/12 18:58:43 by kaye             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:latest

COPY . /APP
WORKDIR /APP

RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf \
	&& apk update \
	&& apk add --no-cache wget \
	&& apk add --no-cache openrc \
	&& apk add --no-cache php7 telegraf nginx \
	&& apk add --no-cache php7-fpm php7-common php7-session php7-iconv php7-json \
	php7-gd php7-curl php7-xml php7-mysqli php7-imap php7-cgi \
	fcgi php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc php7-posix \
	php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom

# install wordpress
RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf \
	&&mkdir -p /var/www/wordpress \
	&& wget https://wordpress.org/latest.tar.gz -P /var/www/wordpress/ \
	&& tar -xzvf /var/www/wordpress/latest.tar.gz -C /var/www/wordpress/ \
	&& rm /var/www/wordpress/latest.tar.gz \
	&& mv /APP/srcs/wp-config.php /var/www/wordpress/wordpress/

# add nginx config
RUN mkdir /run/nginx/
COPY ./srcs/nginx.conf /etc/nginx/conf.d/default.conf

# telegraf config
RUN mkdir /etc/telegraf/
COPY ./srcs/telegraf.conf /etc/telegraf.conf

EXPOSE 5050

CMD ["/bin/sh", "./srcs/init.sh"]